### ISSUE TITLE
Création de transducteurs

### ISSUE THREAD

**Issue by sapk** [sapk/SIT213#24]
Ajouter différents type de transducteur afin de determiner le meilleur.

**Comment by pierro42100** [comment]
Transducteurs créés ainsi que la classe AutomateTransducteur.
Normalement tout roule.
Il faut que je prenne en compte l'argument -transducteur maintenant

**Comment by sapk** [comment]
Pour plus de standardisme il faudrait créer une classes abstraite très similaire à celle-ci pour les transducterus. : https://github.com/sapk-tb/SIT213/blob/etape-5/src/recepteurs/Recepteur.java
Cela eviterais des répétitions dans les sous-classes du coup.
